# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: Papers
    url: papers/
    weight: 11
  - name: Book Reviews
    url: book-reviews/
    weight: 12
  - name: Album Reviews
    url: album-reviews/
    weight: 13
  - name: Parfume Reviews
    url: parfume-reviews/
    weight: 14
  - name: Film Reviews
    url: film-reviews/
    weight: 15
  - name: Blogs
    url: blogs/
    weight: 16